import "package:lashibo/src/book.dart";

List<Book> dummyBooks = <Book>[
  Book(
    title: "On The Origin Of Species",
    description:
        "a scientific book that outlines a theory of how traits are selected by nature, where the tremendous diversity of life on earth came from and how animals and plants came to be distributed across the planet.",
    price: 150000,
    quantityLeft: 20,
    author: "Charles Darwin",
    bookType: BookType.textBook,
    category: Category.science,
    imageAddress: "assets/images/on_the_origin_of_species.jpg",
  ),
  Book(
    title: "Mein Kampf (My Struggle)",
    description:
        "Mein Kampf is a 1925 autobiographical manifesto by Nazi Party leader Adolf Hitler. The work describes the process by which Hitler became antisemitic and outlines his political ideology and future plans for Germany.",
    price: 100000,
    quantityLeft: 0,
    author: "Adolf hitler",
    bookType: BookType.textBook,
    category: Category.biography,
    imageAddress: "assets/images/mein_kampf.jpeg",
  ),
  Book(
    title: "A Brief History Of Time",
    description:
        "A Brief History of Time: From the Big Bang to Black Holes is a book on theoretical cosmology by English physicist Stephen Hawking. It was first published in 1988. Hawking wrote the book for readers who had no prior knowledge of physics.",
    price: 60000,
    quantityLeft: 10,
    author: "Stephen Hawking",
    bookType: BookType.audioBook,
    category: Category.science,
    imageAddress: "assets/images/a_brief_history_of_time.jpeg",
  ),
  Book(
    title: "The Alchemist",
    description:
        "Combining magic, mysticism, wisdom and wonder into an inspiring tale of self-discovery, The Alchemist has become a modern classic, selling millions of copies around the world and transforming the lives of countless readers across generations. Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined. Santiago's journey teaches us about the essential wisdom of listening to our hearts, of recognizing opportunity and learning to read the omens strewn along life's path, and, most importantly, to follow our dreams.",
    price: 80000,
    quantityLeft: 10,
    author: "Paulo Coelho",
    bookType: BookType.audioBook,
    category: Category.adventure,
    imageAddress: "assets/images/the_alchemist.jpg",
  ),
  Book(
    title: "The Art Of War",
    description:
        "Twenty-Five Hundred years ago, Sun Tzu wrote this classic book of military strategy based on Chinese warfare and military thought. Since that time, all levels of military have used the teaching on Sun Tzu to warfare and civilization have adapted these teachings for use in politics, business and everyday life. The Art of War is a book which should be used to gain advantage of opponents in the boardroom and battlefield alike.",
    price: 75000,
    quantityLeft: 15,
    author: "Sun Tzu",
    bookType: BookType.textBook,
    category: Category.nonFiction,
    imageAddress: "assets/images/the_art_of_war.jpg",
  ),
  Book(
    title: "Echoes in Death",
    description:
        "As NY Lt. Eve Dallas and her billionaire husband Roarke are driving home, a young woman—dazed, naked, and bloody—suddenly stumbles out in front of their car. Roarke slams on the brakes and Eve springs into action. Daphne would be a valuable witness, but in her terror and shock the only description of the perp she can offer is repeatedly calling him “the devil”... . What does the devil look like? And where will he show up next? ",
    price: 65000,
    quantityLeft: 20,
    author: "J.D. Robb",
    bookType: BookType.audioBook,
    category: Category.thriller,
    imageAddress: "assets/images/echoes_in_death.jpeg",
  ),
  Book(
    title: "To Kill a Mockingbird",
    description:
        'Compassionate, dramatic, and deeply moving, "To Kill A Mockingbird" takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.',
    price: 70000,
    quantityLeft: 0,
    author: "Harper Lee",
    bookType: BookType.textBook,
    category: Category.classic,
    imageAddress: "assets/images/to_kill_a_mockingbird.jpeg",
  ),
  Book(
    title: "On The Origin Of Species",
    description:
    "a scientific book that outlines a theory of how traits are selected by nature, where the tremendous diversity of life on earth came from and how animals and plants came to be distributed across the planet.",
    price: 150000,
    quantityLeft: 20,
    author: "Charles Darwin",
    bookType: BookType.textBook,
    category: Category.science,
    imageAddress: "assets/images/on_the_origin_of_species.jpg",
  ),
  Book(
    title: "Mein Kampf (My Struggle)",
    description:
    "Mein Kampf is a 1925 autobiographical manifesto by Nazi Party leader Adolf Hitler. The work describes the process by which Hitler became antisemitic and outlines his political ideology and future plans for Germany.",
    price: 100000,
    quantityLeft: 0,
    author: "Adolf hitler",
    bookType: BookType.textBook,
    category: Category.biography,
    imageAddress: "assets/images/mein_kampf.jpeg",
  ),
  Book(
    title: "A Brief History Of Time",
    description:
    "A Brief History of Time: From the Big Bang to Black Holes is a book on theoretical cosmology by English physicist Stephen Hawking. It was first published in 1988. Hawking wrote the book for readers who had no prior knowledge of physics.",
    price: 60000,
    quantityLeft: 10,
    author: "Stephen Hawking",
    bookType: BookType.audioBook,
    category: Category.science,
    imageAddress: "assets/images/a_brief_history_of_time.jpeg",
  ),
  Book(
    title: "The Alchemist",
    description:
    "Combining magic, mysticism, wisdom and wonder into an inspiring tale of self-discovery, The Alchemist has become a modern classic, selling millions of copies around the world and transforming the lives of countless readers across generations. Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined. Santiago's journey teaches us about the essential wisdom of listening to our hearts, of recognizing opportunity and learning to read the omens strewn along life's path, and, most importantly, to follow our dreams.",
    price: 80000,
    quantityLeft: 10,
    author: "Paulo Coelho",
    bookType: BookType.audioBook,
    category: Category.adventure,
    imageAddress: "assets/images/the_alchemist.jpg",
  ),
  Book(
    title: "The Art Of War",
    description:
    "Twenty-Five Hundred years ago, Sun Tzu wrote this classic book of military strategy based on Chinese warfare and military thought. Since that time, all levels of military have used the teaching on Sun Tzu to warfare and civilization have adapted these teachings for use in politics, business and everyday life. The Art of War is a book which should be used to gain advantage of opponents in the boardroom and battlefield alike.",
    price: 75000,
    quantityLeft: 15,
    author: "Sun Tzu",
    bookType: BookType.textBook,
    category: Category.nonFiction,
    imageAddress: "assets/images/the_art_of_war.jpg",
  ),
  Book(
    title: "Echoes in Death",
    description:
    "As NY Lt. Eve Dallas and her billionaire husband Roarke are driving home, a young woman—dazed, naked, and bloody—suddenly stumbles out in front of their car. Roarke slams on the brakes and Eve springs into action. Daphne would be a valuable witness, but in her terror and shock the only description of the perp she can offer is repeatedly calling him “the devil”... . What does the devil look like? And where will he show up next? ",
    price: 65000,
    quantityLeft: 20,
    author: "J.D. Robb",
    bookType: BookType.audioBook,
    category: Category.thriller,
    imageAddress: "assets/images/echoes_in_death.jpeg",
  ),
  Book(
    title: "To Kill a Mockingbird",
    description:
    'Compassionate, dramatic, and deeply moving, "To Kill A Mockingbird" takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.',
    price: 70000,
    quantityLeft: 0,
    author: "Harper Lee",
    bookType: BookType.textBook,
    category: Category.classic,
    imageAddress: "assets/images/to_kill_a_mockingbird.jpeg",
  ),Book(
    title: "On The Origin Of Species",
    description:
    "a scientific book that outlines a theory of how traits are selected by nature, where the tremendous diversity of life on earth came from and how animals and plants came to be distributed across the planet.",
    price: 150000,
    quantityLeft: 20,
    author: "Charles Darwin",
    bookType: BookType.textBook,
    category: Category.science,
    imageAddress: "assets/images/on_the_origin_of_species.jpg",
  ),
  Book(
    title: "Mein Kampf (My Struggle)",
    description:
    "Mein Kampf is a 1925 autobiographical manifesto by Nazi Party leader Adolf Hitler. The work describes the process by which Hitler became antisemitic and outlines his political ideology and future plans for Germany.",
    price: 100000,
    quantityLeft: 0,
    author: "Adolf hitler",
    bookType: BookType.textBook,
    category: Category.biography,
    imageAddress: "assets/images/mein_kampf.jpeg",
  ),
  Book(
    title: "A Brief History Of Time",
    description:
    "A Brief History of Time: From the Big Bang to Black Holes is a book on theoretical cosmology by English physicist Stephen Hawking. It was first published in 1988. Hawking wrote the book for readers who had no prior knowledge of physics.",
    price: 60000,
    quantityLeft: 10,
    author: "Stephen Hawking",
    bookType: BookType.audioBook,
    category: Category.science,
    imageAddress: "assets/images/a_brief_history_of_time.jpeg",
  ),
  Book(
    title: "The Alchemist",
    description:
    "Combining magic, mysticism, wisdom and wonder into an inspiring tale of self-discovery, The Alchemist has become a modern classic, selling millions of copies around the world and transforming the lives of countless readers across generations. Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined. Santiago's journey teaches us about the essential wisdom of listening to our hearts, of recognizing opportunity and learning to read the omens strewn along life's path, and, most importantly, to follow our dreams.",
    price: 80000,
    quantityLeft: 10,
    author: "Paulo Coelho",
    bookType: BookType.audioBook,
    category: Category.adventure,
    imageAddress: "assets/images/the_alchemist.jpg",
  ),
  Book(
    title: "The Art Of War",
    description:
    "Twenty-Five Hundred years ago, Sun Tzu wrote this classic book of military strategy based on Chinese warfare and military thought. Since that time, all levels of military have used the teaching on Sun Tzu to warfare and civilization have adapted these teachings for use in politics, business and everyday life. The Art of War is a book which should be used to gain advantage of opponents in the boardroom and battlefield alike.",
    price: 75000,
    quantityLeft: 15,
    author: "Sun Tzu",
    bookType: BookType.textBook,
    category: Category.nonFiction,
    imageAddress: "assets/images/the_art_of_war.jpg",
  ),
  Book(
    title: "Echoes in Death",
    description:
    "As NY Lt. Eve Dallas and her billionaire husband Roarke are driving home, a young woman—dazed, naked, and bloody—suddenly stumbles out in front of their car. Roarke slams on the brakes and Eve springs into action. Daphne would be a valuable witness, but in her terror and shock the only description of the perp she can offer is repeatedly calling him “the devil”... . What does the devil look like? And where will he show up next? ",
    price: 65000,
    quantityLeft: 20,
    author: "J.D. Robb",
    bookType: BookType.audioBook,
    category: Category.thriller,
    imageAddress: "assets/images/echoes_in_death.jpeg",
  ),
  Book(
    title: "To Kill a Mockingbird",
    description:
    'Compassionate, dramatic, and deeply moving, "To Kill A Mockingbird" takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.',
    price: 70000,
    quantityLeft: 0,
    author: "Harper Lee",
    bookType: BookType.textBook,
    category: Category.classic,
    imageAddress: "assets/images/to_kill_a_mockingbird.jpeg",
  ),Book(
    title: "On The Origin Of Species",
    description:
    "a scientific book that outlines a theory of how traits are selected by nature, where the tremendous diversity of life on earth came from and how animals and plants came to be distributed across the planet.",
    price: 150000,
    quantityLeft: 20,
    author: "Charles Darwin",
    bookType: BookType.textBook,
    category: Category.science,
    imageAddress: "assets/images/on_the_origin_of_species.jpg",
  ),
  Book(
    title: "Mein Kampf (My Struggle)",
    description:
    "Mein Kampf is a 1925 autobiographical manifesto by Nazi Party leader Adolf Hitler. The work describes the process by which Hitler became antisemitic and outlines his political ideology and future plans for Germany.",
    price: 100000,
    quantityLeft: 0,
    author: "Adolf hitler",
    bookType: BookType.textBook,
    category: Category.biography,
    imageAddress: "assets/images/mein_kampf.jpeg",
  ),
  Book(
    title: "A Brief History Of Time",
    description:
    "A Brief History of Time: From the Big Bang to Black Holes is a book on theoretical cosmology by English physicist Stephen Hawking. It was first published in 1988. Hawking wrote the book for readers who had no prior knowledge of physics.",
    price: 60000,
    quantityLeft: 10,
    author: "Stephen Hawking",
    bookType: BookType.audioBook,
    category: Category.science,
    imageAddress: "assets/images/a_brief_history_of_time.jpeg",
  ),
  Book(
    title: "The Alchemist",
    description:
    "Combining magic, mysticism, wisdom and wonder into an inspiring tale of self-discovery, The Alchemist has become a modern classic, selling millions of copies around the world and transforming the lives of countless readers across generations. Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined. Santiago's journey teaches us about the essential wisdom of listening to our hearts, of recognizing opportunity and learning to read the omens strewn along life's path, and, most importantly, to follow our dreams.",
    price: 80000,
    quantityLeft: 10,
    author: "Paulo Coelho",
    bookType: BookType.audioBook,
    category: Category.adventure,
    imageAddress: "assets/images/the_alchemist.jpg",
  ),
  Book(
    title: "The Art Of War",
    description:
    "Twenty-Five Hundred years ago, Sun Tzu wrote this classic book of military strategy based on Chinese warfare and military thought. Since that time, all levels of military have used the teaching on Sun Tzu to warfare and civilization have adapted these teachings for use in politics, business and everyday life. The Art of War is a book which should be used to gain advantage of opponents in the boardroom and battlefield alike.",
    price: 75000,
    quantityLeft: 15,
    author: "Sun Tzu",
    bookType: BookType.textBook,
    category: Category.nonFiction,
    imageAddress: "assets/images/the_art_of_war.jpg",
  ),
  Book(
    title: "Echoes in Death",
    description:
    "As NY Lt. Eve Dallas and her billionaire husband Roarke are driving home, a young woman—dazed, naked, and bloody—suddenly stumbles out in front of their car. Roarke slams on the brakes and Eve springs into action. Daphne would be a valuable witness, but in her terror and shock the only description of the perp she can offer is repeatedly calling him “the devil”... . What does the devil look like? And where will he show up next? ",
    price: 65000,
    quantityLeft: 20,
    author: "J.D. Robb",
    bookType: BookType.audioBook,
    category: Category.thriller,
    imageAddress: "assets/images/echoes_in_death.jpeg",
  ),
  Book(
    title: "To Kill a Mockingbird",
    description:
    'Compassionate, dramatic, and deeply moving, "To Kill A Mockingbird" takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.',
    price: 70000,
    quantityLeft: 0,
    author: "Harper Lee",
    bookType: BookType.textBook,
    category: Category.classic,
    imageAddress: "assets/images/to_kill_a_mockingbird.jpeg",
  ),
];
